repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: 5bf6c09
    hooks:
    -   id: trailing-whitespace
    -   id: flake8
        args:
        # 79 chars is too strict and we don't have 80-char terminals nowadays,
        # 160 chars is too much since it doesn't let us use split view efficiently:
        - --max-line-length=120
        - --ignore=E731
    -   id: check-merge-conflict
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: name-tests-test
        include: magicbus/test/
        args:
        - --django
    -   id: debug-statements
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-byte-order-marker
    -   id: check-case-conflict
    # disabled due to pre-commit/pre-commit-hooks#159
    #-   id: check-docstring-first
    -   id: check-json
    -   id: pretty-format-json
    -   id: check-symlinks
    -   id: check-yaml
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: https://github.com/FalconSocial/pre-commit-mirrors-pep257.git
    rev: v0.3.3
    hooks:
    -   id: pep257
        exclude: magicbus/test

-   repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.1.12
    hooks:
    -   id: remove-tabs

-   repo: https://github.com/Lucas-C/pre-commit-hooks-lxml.git
    rev: v1.1.0
    hooks:
    -   id: forbid-html-img-without-alt-text
