[build-system]
requires = [
    # Essentials
    "setuptools>=34.4",

    # Plugins
    "setuptools_scm>=1.15",
    "setuptools_scm_git_archive>=1.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
